services:
  pvk-cyclop:
    build: .
    container_name: pvk-cyclop
    restart: unless-stopped
    network_mode: host

    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: cyclope_db
      DB_USER: cyclop
      DB_PASSWORD: cyclop123